---

- hosts: all
  become: false 
  pre_tasks:

  - name: install updates (MacOSX)
    tags: always
    package:
      update_homebrew: yes
    when: ansible_distribution == "MacOSX"

- hosts: workstations
  become: false
  roles:
    - workstations
