---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Rocky)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.6.5/terraform_1.6.5_darwin_arm64.zip      
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: don 
      group: admin